name: Email Step Test

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f2003131@ds.study.iitm.ac.in
        run: echo "Hello, this step is named with my email!"
